Models/ViewModels/LocationScheduleForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduler.Models.ViewModels
{
    public class LocationScheduleForm
    {
        public DateTime? Start { get; set; }
        public DateTime? End { get; set; }
        public string City { get; set; }
        public string Status { get; set; }
        public string AppointmentType { get; set; }
    }
}

Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Scheduler.Models;

namespace Scheduler.Controllers
{
    [Authorize]
    public class CalendarController : BaseController
    {
        Scheduler.Models.DAL db = new Scheduler.Models.DAL();
        ApplicationDbContext app_db = new ApplicationDbContext();

        string[] SetAppointmentTimeRoles = new string[] { "Admin", "Planner", "Super Admin" };

        // GET: Calendar
        public ActionResult Index(string loc, int configtype=0)
        {
            return View("Obsolete");
            ViewBag.StatusID = new SelectList(db.Statuses, "ID", "Name");
            ViewBag.LocationID = new SelectList(db.Locations, "Slug", "Name", loc);
            ViewBag.CarrierID = new SelectList(db.Carriers, "ID", "Name");
            ViewBag.ConfigurationType = configtype;

            var location = db.Locations.FirstOrDefault(l => l.Slug == loc);
            if (location == null)
            {
                location = db.Locations.First();
            }

            var user = app_db.Users.First(u => u.UserName == User.Identity.Name);
            var profile = db.UserProfiles.FirstOrDefault(p => p.UserId == user.Id);
            if (profile != null && profile.Location != null)
            {
                location = profile.Location;
            }

            ViewBag.Location = location;
            ViewBag.MinStartTimeString = "00:00";
            ViewBag.MaxEndTimeString = "23:00";
            var configuration = db.GetCurrentConfiguration(location.ID, (LocationConfigurationType)configtype);
            if (configuration != null)
            {
                ViewBag.MinStartTimeString = configuration.MinStartTimeString;
                ViewBag.MaxEndTimeString = configuration.MaxEndTimeString;
            }
            return View();
        }

        public IEnumerable<Status> GetStatuses()
        {
            var statuses = db.Statuses.ToList();
            if (User.IsInRole("DockWorker"))
            {
                var doc_worker_statues = new string[] { "Late", "Complete" };
                statuses = statuses.Where(s => doc_worker_statues.Contains(s.Name)).ToList();
            }
            return statuses;
        }

        public ActionResult Order(string order, string t="ord", string stop_number = "0", string configtype="LUL")
        {
            var locations = db.Locations.ToList();
            ViewBag.StatusID = new SelectList(GetStatuses(), "ID", "Name");
            ViewBag.LocationID = new SelectList(locations, "Slug", "Name");
            ViewBag.CarrierID = new SelectList(db.Carriers, "ID", "Name");
            ViewBag.Order = new Appointment();
            ViewBag.MinStartTimeString = "00:00";
            ViewBag.MaxEndTimeString = "23:00";
            ViewBag.CanUpdateTime = "true";

            if (User.IsInRole("DC Employee") || User.IsInRole("ViewOnly"))
            {
                ViewBag.CanUpdateTime = "false";
            }

            try
            {
                var profile = this.GetCurrentUserProfile();
                var tmw_events = Scheduler.Models.TMW.TMWOrderEvent.GetStops(order, t, revtype1: profile.RevType1);

                //Consolidated orders will have several order numbers in the "batch" of stops.  Only schedule the first order
                order = Convert.ToString(tmw_events.Min(a => a.ord_hdrnumber));
                foreach (var evt in tmw_events)
                {
                    evt.ScheduleLocation = locations.FirstOrDefault(l => l.TMWCodes.Contains(Convert.ToString(evt.stp_city))
                                                                    || l.TMWCodes.Contains(evt.stp_companyid));
                }

                var cfgtype_index = Array.IndexOf(Appointment.TMWAppointmentType, configtype);
                //gotta find the location id for the order
                var current_event = tmw_events.FirstOrDefault(e => e.stp_number == Convert.ToInt32(stop_number));
                if (current_event == null)
                {
                    current_event = tmw_events.FirstOrDefault(e => e.ScheduleLocation != null);
                }
                if (current_event == null)
                {
                    current_event = tmw_events.FirstOrDefault();
                }

                if (current_event == null)
                {
                    throw new Exception("Could not find order in TMW");
                }

                var location = current_event.ScheduleLocation;
                var tmw_orders = Models.TMW.TMWOrder.OrdersInMove(current_event.move_number);
                ViewBag.LocationID = new SelectList(locations, "Slug", "Name", location);

                String stp_number = Convert.ToString(current_event.stp_number);
                var current_appointment = db.Appointments.FirstOrDefault(a => a.OrderNumber == order && a.StopNumber == stp_number);
                if (current_appointment == null)
                {
                    current_appointment = new Appointment()
                    {
                        StartTime = current_event.evt_earlydate,
                        EndTime = current_event.evt_latedate,
                        LocationID = (location != null)?location.ID:0,
                        Location = location,
                        OrderNumber = order,
                        StopNumber = Convert.ToString(current_event.stp_number),
                        AppointmentType = (AppointmentType)cfgtype_index,
                        StatusID = db.Statuses.FirstOrDefault(s => s.Name == "Scheduled").ID
                    };
                }

                ViewBag.CurrentEvent = current_event;
                ViewBag.Order = current_appointment;
                ViewBag.STONumber = current_event.sto_number;
                ViewBag.ConfigurationType = 0;
                ViewBag.OrderNumber = order;
                ViewBag.StopNumber = current_appointment.StopNumber;
                ViewBag.TMWEvents = tmw_events;
                ViewBag.LocationSlug = (location != null) ? location.Slug : "";
                ViewBag.StartDate = current_appointment.StartTime.Date;
                ViewBag.OrderNumberDisplay = String.Join(", ", tmw_orders.Select(to => to.ord_hdrnumber));
                ViewBag.STONumberDisplay = String.Join(", ", tmw_orders.Select(to => to.ord_refnum));
                ViewBag.CarrierDisplay = String.Join(", ", tmw_orders.Select(to => to.ord_carrier));

                LocationConfiguration configuration = null;
                if (location != null)
                {
                    configuration = db.GetCurrentConfiguration(location.ID, (LocationConfigurationType)cfgtype_index);
                }
                
                if (configuration != null)
                {
                    ViewBag.MinStartTimeString = configuration.MinStartTimeString;
                    ViewBag.MaxEndTimeString = configuration.MaxEndTimeString;
                }
                return View(current_appointment);
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();
            }
        }

        public ActionResult ExternalOrder(string LocationID, string configtype = "LUL", 
            string criteria = null, string search_type="ord")
        {
            ViewBag.SearchCriteria = criteria;
            bool order_found = true;
            Appointment order = null;
            if (search_type == "ord") {
                order = db.Appointments.FirstOrDefault(a => a.IsExternal == true && a.OrderNumber == criteria);
            }
            if (search_type == "ref")
            {
                order = db.Appointments.FirstOrDefault(a => a.IsExternal == true && a.STONumber == criteria);
            }
            string location_slug = LocationID;
            var locations = db.Locations.ToList();
            if (order == null)
            {
                order = new Appointment();
                order_found = false;  //suck a dumb hack, but i'm in a hurry now
            }
            else
            {
                location_slug = order.Location.Slug;
                configtype = Appointment.TMWAppointmentType[(int)order.AppointmentType];
            }
            ViewBag.StatusID = new SelectList(GetStatuses(), "ID", "Name");
            ViewBag.LocationID = new SelectList(locations, "Slug", "Name");
            ViewBag.CarrierID = new SelectList(db.Carriers, "ID", "Name");
            ViewBag.Order = order;
            ViewBag.MinStartTimeString = "00:00";
            ViewBag.MaxEndTimeString = "23:00";
            ViewBag.CanUpdateTime = "true";
            ViewBag.StartDate = DateTime.Today;
            if (order_found)
            {
                ViewBag.StartDate = order.StartTime.Date;
            }

            if (User.IsInRole("DockWorker"))
            {
                ViewBag.CanUpdateTime = "false";
            }

            try
            {
                var cfgtype_index = Array.IndexOf(Appointment.TMWAppointmentType, configtype);
                var location = locations.FirstOrDefault(l => l.Slug == location_slug);
                if (location == null)
                {
                    location = locations.First();
                }

                ViewBag.LocationID = new SelectList(locations, "Slug", "Name", location_slug);

                order.LocationID = location.ID;
                ViewBag.ConfigurationTypeString = configtype;
                ViewBag.ConfigurationType = cfgtype_index;
                ViewBag.LocationSlug = location.Slug;
                ViewBag.Location = location;


Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Scheduler.Models;
using Scheduler.Helpers;
using System.Web.Script.Serialization;


namespace Scheduler.Controllers
{
    [Authorize]
    public class ReportController : BaseController
    {
        Scheduler.Models.DAL db = new Scheduler.Models.DAL();
        ApplicationDbContext app_db = new ApplicationDbContext();
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult LocationSchedule(Models.ViewModels.LocationScheduleForm model, string export)
        {
            var locations = db.Locations;
            ViewBag.Status = new SelectList(Models.TMW.TMWOrderStatus.Get(), "ord_status", "ord_status", model.Status);
            ViewBag.AppointmentType = new SelectList(Models.TMW.TMWAppointmentType.Get(), "app_type", "app_type", model.AppointmentType);
            ViewBag.City = new SelectList(locations, "TMWCityName", "Name", model.City);
            if (model.Start.HasValue && model.End.HasValue)
            {
                var report = Models.TMW.DockReportModel.GetReport(model.Start.Value, model.End.Value, model.City, model.Status, model.AppointmentType);
                if (!String.IsNullOrEmpty(export))
                {
                    Response.Clear();
                    Response.AddHeader("Content-Disposition", "attachment; filename=schedule.xlsx");
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

                    var wb = new ClosedXML.Excel.XLWorkbook();
                    var sheet = wb.AddWorksheet("report");
                    ReportHelper.SetRowValues(sheet, 1, new string[] { "Date", "Order Number", "STO Number", "Carrier", "Status", "Appointment Type" }, bold:true);
                    var row_idx = 2;
                    foreach (var item in report)
                    {
                        var report_data = new string[] { "'" + item.Date.ToString("MM/dd/yyyy HH:mm"), item.OrderNumber, item.STONumber, item.Carrier, item.Status, item.AppointmentType };
                        if (item.ConsolidatedSubOrder)
                        {
                            report_data = new string[] { "", item.OrderNumber, item.STONumber, "", "", "" };
                        }
                        ReportHelper.SetRowValues(sheet, row_idx, report_data, bold:item.ConsolidatedFirstOrder);
                        row_idx++;
                        if (item.HasChildOrders)
                        {
                            ReportHelper.SetRowValues(sheet, row_idx, new string[] { "", "Order Number", "STO Number", "Carrier", "Status", "Appointment Type" }, bold:true);
                            row_idx++;
                            foreach(var sub_item in item.ChildOrders)
                            {
                                report_data = new string[] { "", sub_item.SubOrderNumber, sub_item.SubSTONumber, sub_item.SubCarrier, sub_item.SubStatus, sub_item.SubAppointmentType };
                                ReportHelper.SetRowValues(sheet, row_idx, report_data);
                                row_idx++;
                            }
                        }
                    }

                    wb.SaveAs(Response.OutputStream);

                    Response.Flush();
                    Response.End();
                    return null;
                }

                ViewBag.ReportData = report;
                var json = new JavaScriptSerializer().Serialize(report);
                ViewBag.JsonData = json;
                return View(model);
            }


            return View(model);
        }

        public ActionResult CarrierPaySchedule(int order_number = 0)
        {
            var items = Models.TMW.CarrierPayScheduleReport.GetReport(order_number);
            return View(items);
        }

        public ActionResult LoadStatus(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                var po_numbers = search.Split(new char[] { '\n' }).Select(a => a.Trim()).ToArray();
                var profile = GetCurrentUserProfile();
                string billto = null;
                if (profile != null)
                {
                    billto = profile.BillTo;
                }
                var items = Models.TMW.LoadStatusReport.GetReport(po_numbers, billto);
                return View(items);
            }
            return View(new List<Models.TMW.LoadStatusReport>());
        }

        public ActionResult DriverMileage(DateTime? start, DateTime? end)
        {
            var profile = GetCurrentUserProfile();
            string driverid = null;
            if (profile != null)
            {
                driverid = profile.TMWDriverID;
            }
            if (start.HasValue && end.HasValue)
            {
                var reportItems = Models.TMW.MileageReport.GetReport(start.Value, end.Value, driverid);
                return View(reportItems);
            }
            return View();
        }
    }
}

Views/Report/CarrierPaySchedule.cshtml
@model IEnumerable<Scheduler.Models.TMW.CarrierPayScheduleReport>

@{
    ViewBag.Title = "Carrier Pay Schedule";
}

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $('.report-data').DataTable();
        });
    </script>
}

<form method="get">
    <div class="form-group">
        <label class="control-label">Order #</label>
        <input type="text" name="order_number" class="form-contol" />
        <input type="submit" value="Submit" class="btn btn-default" />
        @if(ViewBag.InIframe)
        {
            <input type="hidden" value="1" name="iframe" />
        }
    </div>
</form>
<div id="report-data">
    @if (Model == null)
    {
        <h3>No report criteria</h3>
    }
    @if (Model.Count() == 0)
    {
        <h3>No results</h3>
    }
    @if (Model != null && Model.Count() > 0)
    {
        <table class="dataTable">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Invoice Number</th>
                    <th>Bill To</th>
                    <th>RevType1</th>
                    <th>Invoice Created Date</th>
                    <th>35 Days After Invoice Crated Date</th>
                    <th>Print Date</th>
                    <th>Child Order</th>
                    <th>PayTo ID</th>
                    <th>PayTo Name</th>
                    <th>Carrier</th>
                    <th>Carrier Name</th>
                    <th>Pay Description</th>
                    <th>Pay Amount</th>
                    <th>Pay Status</th>
                    <th>Pay Period</th>
                </tr>
            </thead>
            <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.OrderNumber</td>
                    <td>@item.InvoiceNumber</td>
                    <td>@item.BillTo</td>
                    <td>@item.RevType1</td>
                    <td>@item.InvoiceCreatedDate</td>
                    <td>@item.DaysAfterInvoiceCreated</td>
                    <td>@item.PrintDate</td>
                    <td>@item.ChildOrder</td>
                    <td>@item.PayToID</td>
                    <td>@item.PayToName</td>
                    <td>@item.Carrier</td>
                    <td>@item.PayDescription</td>
                    <td>@item.PayAmount</td>
                    <td>@item.PayStatus</td>
                    <td>@item.PayPeriod</td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>

Views/Report/DriverMileage.cshtml
@model IEnumerable<Scheduler.Models.TMW.MileageReport>
@{
    ViewBag.Title = "DriverMileage";
}

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $('.report-data').DataTable();
        });
    </script>
}

<form method="get">
    <div class="form-group">
        <label class="control-label">Start Date: </label>
        <input type="text" class="datepicker" name="start" value="@Request["start"]" />
        &nbsp;
        <label class="control-label">End Date: </label>
        <input type="text" class="datepicker" name="end" value="@Request["end"]" />
        &nbsp;
        <input type="submit" value="Submit" class="btn btn-default" />
        @if (ViewBag.InIframe)
        {
            <input type="hidden" value="1" name="iframe" />
        }
    </div>
</form>

<div id="report-data">
@if (Model == null)
{
    <h3>No report criteria</h3>
}
@if (Model != null && Model.Count() == 0)
{
    <h3>No results</h3>
}
@if (Model != null && Model.Count() > 0)
{
    <table class="dataTable">
        <thead>
            <tr>
                <th>Year</th>
                <th>Month</th>
                <th>Truck</th>
                <th>Division</th>
                <th>MPG</th>
                <th>IDLE PCT</th>
                <th>Empty Miles</th>
                <th>Loaded Miles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Year</td>
                    <td>@item.Month</td>
                    <td>@item.TruckName</td>
                    <td>@item.Division</td>
                    <td>@item.MPG</td>
                    <td>@item.IDLEPCT</td>
                    <td>@item.EmptyMiles</td>
                    <td>@item.LoadedMiles</td>
                </tr>
            }
        </tbody>
    </table>
}
</div>

Views/Report/LoadStatus.cshtml
@model IEnumerable<Scheduler.Models.TMW.LoadStatusReport>

@{
    ViewBag.Title = "Load Status";
}

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $('.report-data').DataTable();
        });
    </script>
}

<form method="get">
    <div class="form-group">
        <label class="control-label">PO Number:</label>
        <textarea name="search"></textarea>
        <input type="submit" value="Submit" class="btn btn-default" />
        @if(ViewBag.InIframe)
        {
            <input type="hidden" value="1" name="iframe" />
        }
    </div>
</form>
<div id="report-data">
    @if (Model == null)
    {
        <h3>No report criteria</h3>
    }
    @if (Model.Count() == 0)
    {
        <h3>No results</h3>
    }
    @if (Model != null && Model.Count() > 0)
    {
        <table class="dataTable">
            <thead>
                <tr>
                    <th>PO Number</th>
                    <th>Truck</th>
                    <th>Trailer</th>
                    <th>Status</th>
                    <th>Location</th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Reefer Temp</th>
                    <th>LHF</th>
                    <th>Lumper</th>
                </tr>
            </thead>
            <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.PONumber</td>
                    <td>@item.TruckDisplay</td>
                    <td>@item.TrailerDisplay</td>
                    <td>@item.StatusDisplay</td>
                    <td>@item.Location</td>
                    <td>@item.Origin</td>
                    <td>@item.Destination</td>
                    <td>@item.MaxTempDisplay</td>
                    <td>@String.Format("{0:C}", item.LHF)</td>
                    <td>@String.Format("{0:C}", item.Lumper)</td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>

Views/Report/LocationSchedule.cshtml
@model Scheduler.Models.ViewModels.LocationScheduleForm

@{
    ViewBag.Title = "Location Schedule";
}

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $('.report-data table-disabled').DataTable({
            });

            function format_child(child_order) {
                // `d` is the original data object for the row
                return '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">' +
                    '<tr>' +
                        '<td>Full name:</td>' +
                        '<td>' + d.name + '</td>' +
                    '</tr>' +
                    '<tr>' +
                        '<td>Extension number:</td>' +
                        '<td>' + d.extn + '</td>' +
                    '</tr>' +
                    '<tr>' +
                        '<td>Extra info:</td>' +
                        '<td>And any further details here (images etc)...</td>' +
                    '</tr>' +
                '</table>';
            }

            $('#report-data tbody').on('click', 'td.details-control', function () {
                var tr = $(this).closest('tr').next('tr');
                tr.toggle();
            });
        });
    </script>
}

<form method="get">
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control datepicker" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control datepicker" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("City", null, "--- select one --", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", null, "--- select one ---", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AppointmentType", null, "--- select one ---", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                <input type="submit" value="Export" name="export" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div id="report-data">
    @if(ViewBag.ReportData == null)
    {
        <h3>No report criteria</h3>
    }
    @if(ViewBag.ReportData != null && ViewBag.ReportData.Count == 0)
    {
        <h3>No results</h3>
    }
    @if(ViewBag.ReportData != null && ViewBag.ReportData.Count > 0)
    {
        <table class="dataTable">
            <thead>
            <tr>
                <th></th>
                <th>Date</th>
                <th>Order Number</th>
                <th>STO Number</th>
                <th>Carrier</th>
                <th>Status</th>
                <th>Appointment Type</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th></th>
                <th>Date</th>
                <th>Order Number</th>
                <th>STO Number</th>
                <th>Carrier</th>
                <th>Status</th>
                <th>Appointment Type</th>
            </tr>
            </tfoot>
            <tbody>
                @{ 
                    var outrow = 0;
                }
        @for(var i = 0;i < ViewBag.ReportData.Count; i++)
        {
            var item = ViewBag.ReportData[i];
            var do_output = item.ConsolidatedSubOrder == false;
            var do_bold = item.ConsolidatedFirstOrder == true;
            if (item.ConsolidatedFirstOrder || !item.ConsolidatedSubOrder)
            {
                outrow++;
            }
            <tr class='@((outrow%2==0)?"":"alt-row") @(do_bold?"consolidated-first":"")'>
                <td class='@(item.HasChildOrders?"details-control":"")'></td>
                <td>@(do_output?item.Date.ToString("MM/dd/yyyy HH:mm"):"")</td>
                <td>@Html.ActionLink((String)item.OrderNumber, "Order", "Calendar", new { t="ord", order = item.OrderNumber }, null)</td>
                <td>@item.STONumber</td>
                <td>@(do_output?item.Carrier:"")</td>
                <td>@(do_output?item.Status:"")</td>
                <td>@(do_output?item.AppointmentType:"")</td>
            </tr>
            if(item.HasChildOrders)
            {
                <tr class="child-order" style="display:none">
                    <td colspan="7">
                        <table style="margin-left:20px" class="dataTable">
                            <tr>
                                <th>Order Number</th>
                                <th>STO Number</th>
                                <th>Carrier</th>
                                <th>Status</th>
                                <th>Appointment Type</th>
                            </tr>
                            @foreach(var child in item.ChildOrders)
                            {
                            <tr>
                                <td>@child.SubOrderNumber</td>
                                <td>@child.SubSTONumber</td>
                                <td>@child.SubCarrier</td>
                                <td>@child.SubStatus</td>
                                <td>@child.SubAppointmentType</td>
                            </tr>
                            }
                        </table>
                    </td>
                </tr>
            }
        }
            </tbody>
        </table>
    }
</div>